### PR TITLE
Use newer freedesktop platform 23.08

### PR DESCRIPTION
**Pull request by der-eismann**

### CODE REVIEW

**Comment by slouken** [comment]
I’m assuming we want to stay with the LTS runtime. @smcv, is that right?

**Comment by der-eismann** [comment]
It would be new to me that any of the freedesktop SDK versions are LTS. What exactly do you mean?

**Comment by smcv** [comment]
@der-eismann, thanks for the reminder to look at this.

> I’m assuming we want to stay with the LTS runtime. @smcv, is that right?

There's no particular difference between the runtimes, other than 1 year of newer libraries. They all have the same support lifetime: this is not like Ubuntu where 22.04 has a longer support lifetime than 23.04.

I think the best thing we can do for users is to migrate to the new runtime, to avoid a situation where Steam Link might be the only thing that is still pulling in the old one.

However, instead of accepting this PR as-is, I think we should ideally migrate Valve-internal infrastructure to build new Steam Link proprietary binaries in a 23.08-based container (I can look at providing that container today), build a new set of binaries in that environment, and then test an update that makes two changes simultaneously: switches the proprietary binaries to the new version, and switches the runtime to 23.08. I think that's what we did for the 21.08 -> 22.08 transition.

**Comment by der-eismann** [comment]
Thanks for the detailed answer! Feel free to close this PR then :slightly_smiling_face:

**Comment by smcv** [comment]
The beta branch is now using 23.08.

**Pull request closed without merging**
